name: readme-monthly

on:
  workflow_dispatch:

  schedule:
    - cron: "0 2 1 * *"

permissions:
  contents: write

jobs:
  generate-readme:
    uses: Infrastrukturait/READMEgen/.github/workflows/generate-readme.yml@main
    with:
      config: README.yml
      output: README.md
      commit_message: "chore: regenerate README [skip ci]"
